Feature lidar setup
UbiquityRobotics/learn pull request #43
Opened 2022-02-07 14:59 UTC by JanezCim

Added LS lidar instructions to learn pages. This is a draft pull request because more discussion is yet to be done:

Unresolved questions:

- Since we are likely to add the LD lidar, we need to make sure we have the tutorials prepared for that. Now the biggest issue is that i still dont know how we are going to be calling this lidar in the tutorials. Internally we define them as LS and LD lidars, but since we want to be branding the LS lidar as our own, what the heck do we call it in the tutorials? I've refered to it as magni-default lidar or ubiquity robotics lidar? 
- The same question for little LS lidar - are we branding it as UR lidar? If yes, how do we call it.

Please rewiew the tutorials and give me feedback. Thanks!

2022-02-10 14:05 UTC, MoffKalast requested changes
Found a few issues to resolve, also we should probably discuss the best way to launch lidars on our images in a more seamless fashion.

2022-02-10 14:05 UTC, MoffKalast commented on doing_more/ls_lidar_setup_kinetic.md
> +Ubuntu 18.04
16.04?

2022-02-11 07:41 UTC, JanezCim commented on doing_more/ls_lidar_setup_common.md
> +In this document it is described how to set up the LS301 lidar on the Magni.
which.... is also not bad :D

yes, will fix this

2022-02-11 07:43 UTC, JanezCim commented on doing_more/ls_lidar_setup_common.md
> +# Setting up ubiquity robotics default lidar
Ok, true, do you have any suggestion as to what to call it? Im fine with LSN301 and LD06 but we all need to agree on calling it that then. See description of PR for more comments about naming?

2022-02-11 07:46 UTC, JanezCim commented on doing_more/ls_lidar_setup_common.md
> +
yeah if those lidars will become default on magni, maybe the launches could be in magni repo as well.

2022-02-11 07:49 UTC, JanezCim commented on doing_more/ls_lidar_setup_common.md
> +    sudo nano /etc/network/interfaces
Ah yes, im now finding ways to make this work also on focal, Untill then i've just added a todo in a comment

2022-02-14 15:11 UTC, MoffKalast commented on doing_more/ls_lidar_setup_common.md
> +# Setting up ubiquity robotics default lidar
Right I missed that part of the description, I suppose LS-N301 and LD06 is good. Full names would be LeiShen N301 and LDRobot LD06.

2022-02-14 16:35 UTC, MoffKalast commented
> You mean that on the magni_robot repo, noetic branch? Any idea how to make it more seamless? Id be happy to hear it. :)

Yeah I think it may be worthwhile to have it as a yaml param much like sonars_installed, except lidar_type or something similar. Much like it's done [in ezmap kinetic](https://github.com/UbiquityRobotics/ezmap/blob/8a0bd219d84acf260377a768f7384a94147ea0a1/ezmap_bringup/launch/core.launch#L101) right now for the time being.

2022-02-28 14:13 UTC, JanezCim commented
@MoffKalast @mjstn i've now renamed the ls lidar into ur50 lidar in all the tutorials. i've also implemented @MoffKalast s suggestions. I think its now ready to be reviewed. I think we think about adding tutorials for other lidars in other PRs

2022-03-09 10:30 UTC, JanezCim commented
@MoffKalast and @mjstn this has been stale for some time now but its ready to be reviewed and merged if all is alright.

2022-03-17 17:58 UTC, MoffKalast approved these changes
Ok yeah the changes seem good for now, looks alright to me. There will always be a few more issues found once it's hosted, so we can everything that's noted later.

2022-03-18 16:27 UTC, merged